name: Issue Templates
description: Choose the appropriate issue type
title: "Choose an issue type"
blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/harveyzhang814/youtube-downloader-gui/discussions
    about: Please ask and answer questions here.
